### ISSUE TITLE
Roadmap for Blaze v3 ⚡🥁

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#128]
### It's time for v3!
Blaze v3 will feature an improved interface along with a bunch of new features to facilitate and improve the flow of file sharing :tada: 

Here are the tasks in focus for this release:
- [x] **Subtle redesign** of Rooms page. Done! #132 
- ~**Activity stream** - To show some stats about files shared by the user from the locally stored data.~
  Feature cancelled for the time being, may pick it up later.
- [x] #151 Done! 2a32ff34cbf171d76cf327008e4a4a01d1e85bb8
- [x] #25  - Highly requested, would include a way to change nickname. Open to suggestions for other controls in settings.  Done! e5b958e120c8d74c8d34d3843fd728b97811f9c1
- [x] #65 - Local rooms would reduce the room creation step just for sharing files in your local network. Done! c0d64282b8776e228f68a647e2064bffd7b04578
- [x] #126 Done! d92e39e4010249944204fc1d32f3912f9e9e5e75
- [x] Additional **PWA level integrations**:
  - [x] Physical install button on Blaze UI. Done! #132
  - [x] App shortcuts for:
    - [x] Local rooms. Done! 1d1967a2ada8d7d1a0df7468e46217591990ad4c
    - [x] Instant rooms. #133 
- [x] Fixing #84 Done! 076bdf2fb9ec7b2bbd620677b762fc6391bd4d3a
- [x] #109 Done! 44e3d6687a4bd8789249af67b7b3f05fb0087938
- [x] #143 
- [x] #150 
<br />
Already open issues would also be worked upon if time permits or other contributors can help. But the primary focus will be on the above issues :slightly_smiling_face:

**Comment by blenderskool** [comment]
Yay! 🚀
